apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apinto
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: openapi
      port: {{ .Values.service.openApiPort }}
      targetPort: {{ .Values.service.openApiPort }}
    - name: raft
      port: {{ .Values.service.raftPort }}
      targetPort: {{ .Values.service.raftPort }}
  selector:
    app: {{ .Release.Name }}-apinto
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-apinto
spec:
  serviceName: {{ .Release.Name }}-apinto
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apinto
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apinto
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: apinto
          image: {{ .Values.image }}:{{ .Values.tag }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
            - containerPort: {{ .Values.service.openApiPort }}
            - containerPort: {{ .Values.service.raftPort }}
          volumeMounts:
            - name: apinto-config
              mountPath: /etc/apinto/config.yml
              subPath: config.yml
            - name: apinto-data
              mountPath: /var/lib/apinto
            - name: apinto-logs
              mountPath: /var/log/apinto
      volumes:
        - name: apinto-config
          configMap:
            name: {{ include "apinto.fullname" . }}-config
            items:
              - key: config.yml
                path: config.yml
        - name: apinto-logs
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: apinto-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "10Gi" }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
