{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apipark-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1m" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/mysql_username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/mysql_password
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/mysql_database
    - secretKey: MYSQL_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/mysql_host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/mysql_port
    - secretKey: REDIS_ADDR
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/redis_addr
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/redis_password
    - secretKey: INFLUX_TOKEN
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/influx_token
    - secretKey: APIPARK_ADMIN_USER
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/apipark_admin_user
    - secretKey: APIPARK_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/apipark_admin_password
{{- end }}
