{{- if and .Values.secrets.enabled .Values.secrets.aws.secretProviderClassName }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.aws.secretProviderClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secrets.aws.region }}
    objects: |
      - objectName: "{{ .Values.secrets.aws.secretObjectName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "mysql_username"
            objectAlias: "mysql-username"
          - path: "mysql_password"
            objectAlias: "mysql-password"
          - path: "mysql_database"
            objectAlias: "mysql-database"
          - path: "redis_password"
            objectAlias: "redis-password"
          - path: "apipark_admin_user"
            objectAlias: "apipark-admin-user"
          - path: "apipark_admin_password"
            objectAlias: "apipark-admin-password"
          - path: "influx_token"
            objectAlias: "influx-token"
          - path: "apinto_admin_token"
            objectAlias: "apinto-admin-token"
          - path: "ADMIN_PASSWORD"
            objectAlias: "ADMIN_PASSWORD"
  secretObjects:
    - secretName: {{ .Values.secrets.k8sSecretName }}
      type: Opaque
      data:
        - objectName: "mysql-username"
          key: "MYSQL_USERNAME"
        - objectName: "mysql-password"
          key: "MYSQL_PASSWORD"
        - objectName: "mysql-database"
          key: "MYSQL_DATABASE"
        - objectName: "redis-password"
          key: "REDIS_PASSWORD"
        - objectName: "apipark-admin-user"
          key: "APIPARK_ADMIN_USER"
        - objectName: "apipark-admin-password"
          key: "APIPARK_ADMIN_PASSWORD"
        - objectName: "influx-token"
          key: "INFLUX_TOKEN"
        - objectName: "apinto-admin-token"
          key: "APINTO_ADMIN_TOKEN"
        - objectName: "ADMIN_PASSWORD"
          key: "ADMIN_PASSWORD"
{{- end }}
