apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3100
      name: http
  selector:
    app: {{ .Release.Name }}-loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-loki
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-loki
    spec:
      containers:
        - name: loki
          image: {{ .Values.image }}
          args: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: 3100
              name: http
