apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      name: http
  selector:
    app: {{ .Release.Name }}-grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.image }}
          ports:
            - containerPort: 3000
              name: http
